[tool.poetry]
name = "geometry-libary"
version = "0.1.0"
description = ""
authors = ["ichiri0 <ivankochettov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
